name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        use: actions/checkout@v3
      - name: Install
        use: actions/setup-node@3
        with:
          node-version: 18.7.0
          cache: yarn
      - name: Build
        run: yarn install --immutable --immutable-cache --check-cache
